---
title: "Chapter X - R Notebook"
author: "Salomé Carcy"
date: "`r format(Sys.Date(), '%d %B %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true

---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(fig.width = 5, fig.height = 5,
                      warning=FALSE, message=FALSE,
                      root.dir = "~/Projects/phd/")
```


# IMPORT

## Import librairies
```{r import-librairies}
library(ggplot2)
library(RColorBrewer)
library(cowplot)
library(tidyverse)
library(dplyr)
library(Seurat)
library(SCpubr)
library(patchwork)

source("~/Projects/phd/scripts/colors_universal.R")
```

## Import data
```{r import-data}
summary.annotated <- read.csv("~/Projects/HumanThymusProject/data/human-thymus/SpatialData/proportion_cluster_across_regions.csv")
```




# FUNCTIONS
```{r define-functions}

```




# ANALYSIS

## Analysis 1
```{r analysis-1}

```


## Analysis 2
```{r analysis-2}

```

## Analysis 1
```{r analysis-1}

```


## Analysis 2
```{r analysis-2}

```

## Analysis 3
```{r analysis-3}

```


## Analysis 4
```{r analysis-4}

```




# SESSION INFO
```{r}
sessionInfo()
```


