---
title: "Chapter 2 - Figure 2"
author: "Salomé Carcy"
date: "`r format(Sys.Date(), '%d %B %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true

---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(fig.width = 5, fig.height = 5,
                      warning=FALSE, message=FALSE,
                      root.dir = "~/Projects/phd/")
```


# IMPORT

## Import librairies
```{r import-librairies}
library(ggplot2)
library(cowplot)
library(tidyverse)
library(dplyr)
library(Seurat)
library(harmony)
library(SCpubr)
library(patchwork)

source("~/Projects/phd/scripts/colors_universal.R")
```

## Import data
```{r import-data}
seur_integrated <- readRDS("./data/seurat_objects/seurat_human_integrated_object_23_12_01.rds")
DimPlot(seur_integrated, reduction="umap_integrated", cols = cols_integrated)
```




# FIGURES
## Figure 2: integrated data by tissue
Show the cells colored by tissue. Split by tissue to show overlap.
```{r fig2, fig.width=5, fig.height=5}
# order thymus first
seur_integrated@meta.data$tissue <- factor(seur_integrated@meta.data$tissue, levels=c("Thymus", "PBMC"))

do_DimPlot(
  seur_integrated,
  group.by="tissue",
  split.by="tissue",
  colors.use=cols_tissue,
  shuffle=T,
  order=NULL,
  pt.size=4,
  border.size=2,
  raster=T,
  raster.dpi = 2048
  )
# ggsave("~/Projects/phd/scripts/chapter_02/figs/figs_unfinished/ch2_fig2_bis.jpeg", width=12, height=5)
```



## Figure 5: integrated clustering
```{r fig5_clusters, fig.width=5, fig.height=5}
# All data
do_DimPlot(
    sample = seur_integrated,
    group.by="clusters_integrated_data",
    colors.use = cols_integrated,
    label=T,
    legend.position="none",
    pt.size=4,
    raster=T,
    raster.dpi = 2048
)
# ggsave("~/Projects/phd/data/figures/chapter_02/figs_unfinished/section1/ch2_fig5_clusters.pdf", width=6, height=6)
```

```{r fig5_clusters_by_tissue, fig.width=20, fig.height=5}
# Highlight thymocytes
do_DimPlot(
    sample = seur_integrated,
    group.by="clusters_integrated_data",
    split.by="tissue",
    colors.use = cols_integrated,
    legend.position="none",
    pt.size=5,
    raster=T,
    raster.dpi = 2048
)
# ggsave("~/Projects/phd/data/figures/chapter_02/figs_unfinished/section1/ch2_fig5_clusters_by_tissue.pdf", width=18, height=6)
```

```{r fig5_markergenes, fig.height=10, fig.width=8}
# Supp Fig 3A, but only on thymocytes
thymocytes_cellid <- rownames(seur_integrated@meta.data[seur_integrated@meta.data$tissue=="Thymus",])
length(thymocytes_cellid)

genes_dotplot <- c(
  "PTCRA", "RAG1", # CD4 ISP
  "MKI67", "CDK1", # CD4 ISP (P)
  "CD4", "CD8A", "CD8B", "CD1C", "AQP3", # DP
  "CCR9", "SATB1", # ab T entry
  "EGR1", "EGR3", "NR4A1", # Agonist
  "CD8A", "PDCD1", "GNG4", # CD8aa
  "TRDC", "TRGC2", # GD
  "IKZF4", "FOXP3", "CTLA4", "IL2RA", # Treg
  "STAT1", "IFI6", # IFN sig
  "CD8B", "RUNX3", "LINC02446", # CD8
  "CD4", "ZBTB7B", "CD40LG", # CD4
  "CCR7", "SELL", "S1PR1",  #"IL7R", # Naive / exit
  "FOS", "JUN", "JUNB", # AP1 signaling
  "EOMES", "TBX21", "RORA", "RORC", "GZMK", "GZMB", "GNLY", "PRF1", "NKG7", "KLRB1", "IFNG", "CCR6" # Effector
  )

# DotPlot
fig5_p1 <- do_DotPlot(
  sample=seur_integrated[,thymocytes_cellid],
  features=genes_dotplot,
  group.by = "clusters_integrated_data",
  legend.position = "right",
  use_viridis = T,
  viridis.palette = "B",
  flip=T
  )+
  # coord_flip()+
  theme(axis.text.x=element_text(angle=0, hjust=0.5),
        axis.text.y=element_text(face="italic"))

# Barplot of nb of cells
fig5_p2 <- seur_integrated@meta.data %>%
  as_data_frame() %>%
  filter(tissue=="Thymus") %>%
  group_by(clusters_integrated_data, tcell_lineage) %>%
  count() %>%
  ggplot(aes(x=clusters_integrated_data, y=n, fill=tcell_lineage))+
  geom_bar(stat="identity")+
  scale_fill_manual(values=cols_lineages, name="Cell hashing")+
  scale_y_continuous(expand = c(0, 0))+
  # scale_x_discrete(position="top")+
  labs(x="", y="Number of thymocytes")+
  theme_cowplot()

# Combine
fig5_p2 / fig5_p1 + plot_layout(heights = c(1, 4))
# ggsave("~/Projects/phd/scripts/chapter_02/figs/figs_unfinished/ch2_fig5_markergenes.pdf", width=8, height=10)
```

```{r fig5_tissue_distribution}
seur_integrated@meta.data %>%
  as_data_frame() %>%
  group_by(clusters_integrated_data, tissue) %>%
  count() %>%
  mutate(tissue=as.character(tissue)) %>%
  # plot
  ggplot(aes(x=clusters_integrated_data, y=n, fill=tissue))+
  geom_bar(stat="identity", position="fill")+
  scale_fill_manual(values=cols_tissue, name="Tissue")+
  theme_cowplot()+
  labs(x="Clusters", y="Frequency")
# ggsave("~/Projects/phd/scripts/chapter_02/figs/figs_unfinished/ch2_fig5_tissue_distribution.pdf", width=7, height=4)
```












# SESSION INFO
```{r}
sessionInfo()
```


