---
title: "Chapter 2 - R Notebook"
author: "Salomé Carcy"
date: "`r format(Sys.Date(), '%d %B %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true

---


# IMPORT

## Import librairies
```{r import-librairies}
library(ggplot2)
library(RColorBrewer)
library(cowplot)
library(tidyverse)
library(dplyr)
library(Seurat)
library(SCpubr)
library(patchwork)
library(ggalluvial)

source("~/Projects/phd/scripts/colors_universal.R")
```

## Import data
```{r import-data}
seur_integrated <- readRDS("./data/seurat_objects/seurat_human_integrated_object_23_12_01.rds")

seur_thym <- list(
  "cd4"=readRDS("./data/seurat_objects/thymus_objects/seurat_filtered_harmony_02_15_23_thymus.cd4.RDS"),
  "cd8"=readRDS("./data/seurat_objects/thymus_objects/seurat_filtered_harmony_02_15_23_thymus.cd8.RDS"),
  "nkt"=readRDS("./data/seurat_objects/thymus_objects/seurat_filtered_harmony_02_15_23_thymus.nkt.RDS"),
  "mait"=readRDS("./data/seurat_objects/thymus_objects/seurat_filtered_harmony_02_15_23_thymus.mait.RDS"),
  "gdt"=readRDS("./data/seurat_objects/thymus_objects/seurat_filtered_harmony_02_15_23_thymus.gd.RDS")
)
```




# PREPARE DATA
Do a bit of cleanup
```{r data-cleanup}
# sanity check
table(rownames(seur_integrated@meta.data[rownames(seur_integrated@meta.data)%in%rownames(seur_thym$mait@meta.data),]) == rownames(seur_thym$mait@meta.data), useNA="ifany"
)

# add column "clusters per lineage"
seur_thym$cd4@meta.data$clusters_per_lineage <- seur_integrated@meta.data[rownames(seur_integrated@meta.data)%in%rownames(seur_thym$cd4@meta.data), "clusters_per_lineage"]
seur_thym$cd8@meta.data$clusters_per_lineage <- seur_integrated@meta.data[rownames(seur_integrated@meta.data)%in%rownames(seur_thym$cd8@meta.data), "clusters_per_lineage"]
seur_thym$nkt@meta.data$clusters_per_lineage <- seur_integrated@meta.data[rownames(seur_integrated@meta.data)%in%rownames(seur_thym$nkt@meta.data), "clusters_per_lineage"]
seur_thym$mait@meta.data$clusters_per_lineage <- seur_integrated@meta.data[rownames(seur_integrated@meta.data)%in%rownames(seur_thym$mait@meta.data), "clusters_per_lineage"]
seur_thym$gdt@meta.data$clusters_per_lineage <- seur_integrated@meta.data[rownames(seur_integrated@meta.data)%in%rownames(seur_thym$gdt@meta.data), "clusters_per_lineage"]

# add column "clusters integrated"
seur_thym$cd4@meta.data$clusters_integrated_data <- seur_integrated@meta.data[rownames(seur_integrated@meta.data)%in%rownames(seur_thym$cd4@meta.data), "clusters_integrated_data"]
seur_thym$cd8@meta.data$clusters_integrated_data <- seur_integrated@meta.data[rownames(seur_integrated@meta.data)%in%rownames(seur_thym$cd8@meta.data), "clusters_integrated_data"]
seur_thym$nkt@meta.data$clusters_integrated_data <- seur_integrated@meta.data[rownames(seur_integrated@meta.data)%in%rownames(seur_thym$nkt@meta.data), "clusters_integrated_data"]
seur_thym$mait@meta.data$clusters_integrated_data <- seur_integrated@meta.data[rownames(seur_integrated@meta.data)%in%rownames(seur_thym$mait@meta.data), "clusters_integrated_data"]
seur_thym$gdt@meta.data$clusters_integrated_data <- seur_integrated@meta.data[rownames(seur_integrated@meta.data)%in%rownames(seur_thym$gdt@meta.data), "clusters_integrated_data"]
```




# FUNCTIONS
```{r define-functions}
plot_UMAP <- function(seurobj, group="clusters_per_lineage", col_vector){
  p <- ggrastr::rasterise(
    do_DimPlot(
      seurobj,
      group.by = group,
      colors.use = col_vector,
      legend.position = "right"
    ),
    layers = "Point",
    dpi = 300
  ) +
    theme(
      axis.ticks = element_blank(),
      axis.text = element_blank(),
      axis.line = element_blank(),
      panel.border = element_rect(
        colour = "black",
        fill = NA,
        size = 1
      ),
      axis.title = element_text(hjust = 0)
    )
  return(p)
}

# Plot correspondance between integrated clusters and cluster per lineage
plot_alluvial <- function(seurobj){
  p <- seurobj@meta.data %>%
    as_tibble() %>%
    group_by(clusters_integrated_data, clusters_per_lineage) %>%
    summarise(ncells=n()) %>%
    ungroup() %>%
    # plot
    ggplot(aes(axis1=clusters_integrated_data, axis2=clusters_per_lineage, y=ncells)) +
    geom_alluvium(aes(fill=clusters_integrated_data))+
    geom_stratum()+
    geom_text(stat="stratum", aes(label=after_stat(stratum)))+
    scale_fill_manual(values=cols_integrated)+
    scale_x_continuous(breaks = 1:2, labels = c("Clusters integrated data", "Clusters per lineage"))+
    labs(y="# cells")+
    theme_bw()+
    theme(legend.position="none",
          panel.grid = element_blank())
  return(p)
}

plot_barplot <- function(seurobj){
  p <- seurobj@meta.data %>%
    as_tibble() %>%
    group_by(clusters_integrated_data, clusters_per_lineage) %>%
    summarise(ncells=n()) %>%
    # group_by(clusters_per_lineage) %>%
    # mutate(freq=ncells*100/sum(ncells)) %>%
    ungroup() %>%
    # plot
    ggplot(aes(x=clusters_per_lineage, y=ncells, fill=clusters_integrated_data)) +
    geom_bar(stat="identity")+
    # geom_text(aes(label=clusters_integrated_data, y=ncells), vjust=1.5)+
    scale_fill_manual(values=cols_integrated, name="Clusters\nintegrated data")+
    # scale_y_continuous(expand=c(0,0))+
    # scale_x_continuous(breaks = 1:2, labels = c("Clusters integrated data", "Clusters per lineage"))+
    labs(x="", y="# cells")+
    theme_bw()+
    guides(fill=guide_legend(reverse=T, ncol=2))+
    theme(panel.grid = element_blank(),
          axis.text.x=element_text(angle=45, hjust=1))
  return(p)
}

# Plot marker genes dotplot
plot_DotPlot <- function(seurobj, features, scaling=F){
  # get plot data
  p <- Seurat::DotPlot(
    seurobj,
    group.by="clusters_per_lineage",
    features=features,
    scale=scaling
  )
  # plot in personalized way
  p <- ggplot(p$data, aes(x=id, y=features.plot, fill=avg.exp.scaled, size=pct.exp))+
    geom_point(color="black", shape=21)+
    scale_size_continuous(range=c(0,6), limits=c(0,100), name="%cells\nexpressing\ngene")+
    theme_bw()+
    theme(axis.text.y=element_text(face="italic"),
          axis.text.x=element_text(angle=45, hjust=1))+
    labs(y="", x="")
  # different color scale if scaled or not
  if(scaling==T){
    p <- p + scale_fill_gradient2(low=scales::muted("blue"), high=scales::muted("red"), name="z-score\nnormalized\navg expression")
  } else{
    p <- p + viridis::scale_fill_viridis(option="B", direction=-1, name="normalized\navg expression")
  }
  return(p)
}

# Get marker genes and plot
get_markergenes <- function(seurobj){
  Idents(seurobj) <- "clusters_per_lineage"
  markergenes <- FindAllMarkers(
    seurobj,
    test.use = 'wilcox',
    logfc.threshold = 0.4,
    min.pct = 0.3,
    only.pos = TRUE
  )
  return(markergenes)
  # markergenes_list <- markergenes %>%
  #   mutate(cluster=as.character(cluster)) %>%
  #   arrange(cluster) %>%
  #   filter(p_val_adj<0.05) %>%
  #   group_by(cluster) %>%
  #   top_n(-5, p_val_adj) %>%
  #   top_n(5, avg_log2FC) %>%
  #   ungroup() %>%
  #   pull(gene) %>% unique()
  # 
  # # plot
  # p <- Seurat::DotPlot(
  #   seurobj,
  #   group.by="clusters_per_lineage",
  #   features=markergenes_list,
  #   scale=scaling
  # )
  # # plot in personalized way
  # p <- ggplot(p$data, aes(x=features.plot, y=id, fill=avg.exp.scaled, size=pct.exp))+
  #   geom_point(color="black", shape=21)+
  #   scale_size_continuous(range=c(0,6), limits=c(0,100), name="%cells\nexpressing\ngene")+
  #   theme_bw()+
  #   theme(axis.text.x=element_text(face="italic", angle=45, hjust=1))+
  #   labs(y="", x="")
  # # different color scale if scaled or not
  # if(scaling==T){
  #   p <- p + scale_fill_gradient2(low=scales::muted("blue"), high=scales::muted("red"), name="z-score\nnormalized\navg expression")
  # } else{
  #   p <- p + viridis::scale_fill_viridis(option="B", direction=-1, name="normalized\navg expression")
  # }
  # return(p)
}

```




# PLOT SEURAT OBJECTS

## CD4
```{r cd4, fig.width=6, fig.height=15, message=F}
cd4_p1 <- plot_UMAP(seur_thym$cd4, col_vector=cols_thym_cd4)
# plot_alluvial(seur_thym$cd4)
cd4_p2 <- plot_barplot(seur_thym$cd4)
# cd4_p3 <- plot_markergenes(seur_thym$cd4)

# get marker genes
markergenes_cd4 <- get_markergenes(seur_thym$cd4)
markergenes_cd4_list <- markergenes_cd4 %>%
  mutate(cluster=as.character(cluster)) %>%
  arrange(cluster) %>%
  filter(p_val_adj<0.05) %>%
  ungroup() %>%
  group_by(cluster) %>%
  top_n(-5, p_val_adj) %>%
  top_n(5, avg_log2FC) %>%
  ungroup() %>%
  pull(gene) %>% unique()
markergenes_cd4_list <- append(markergenes_cd4_list, "PTCRA", after=1)
markergenes_cd4_list <- append(markergenes_cd4_list, "ZBTB7B", after=18)

cd4_p3 <- plot_DotPlot(seurobj = seur_thym$cd4, features=markergenes_cd4_list, scaling=T)

# combine plots !
# cd4_p1 + cd4_p2 + cd4_p3 + plot_layout(widths=c(1,1,1.5))
cd4_p1 / cd4_p2 / cd4_p3 + plot_layout(heights=c(1,1,2))
# ggsave("~/Projects/phd/data/figures/chapter_02/figs_unfinished/section2/appendix1_markergenes/ch2_suppfigure_cd4_vertical.pdf", width=6, height=15)
```


## CD8
```{r cd8, fig.width=6, fig.height=15, message=F}
cd8_p1 <- plot_UMAP(seur_thym$cd8, col_vector=cols_thym_cd8)
cd8_p2 <- plot_barplot(seur_thym$cd8)
# cd8_p3 <- plot_markergenes(seur_thym$cd8)

# get marker genes
markergenes_cd8 <- get_markergenes(seur_thym$cd8)
markergenes_cd8_list <- markergenes_cd8 %>%
  mutate(cluster=as.character(cluster)) %>%
  arrange(cluster) %>%
  filter(p_val_adj<0.05) %>%
  # remove any genes that are marker in more than 2 clusters
  # group_by(gene) %>%
  # filter(n_distinct(cluster)<=2) %>%
  ungroup() %>%
  group_by(cluster) %>%
  top_n(-5, p_val_adj) %>%
  top_n(5, avg_log2FC) %>%
  ungroup() %>%
  # filter(avg_log2FC>1) %>%
  pull(gene) %>% unique()
markergenes_cd8_list <- append(markergenes_cd8_list, "RUNX3", after=15)
markergenes_cd8_list <- append(markergenes_cd8_list, "CCR9", after=16)
markergenes_cd8_list <- append(markergenes_cd8_list, "CCR7", after=23)

cd8_p3 <- plot_DotPlot(seurobj = seur_thym$cd8, features=markergenes_cd8_list, scaling=T)

# combine plots!
# cd8_p1 + cd8_p2 + cd8_p3 + plot_layout(widths=c(1,1,1.5))
cd8_p1 / cd8_p2 / cd8_p3 + plot_layout(heights=c(1,1,2))
# ggsave("~/Projects/phd/data/figures/chapter_02/figs_unfinished/section2/appendix1_markergenes/ch2_suppfigure_cd8_vertical.pdf", width=6, height=15)
```


## iNKT
```{r nkt, fig.width=6, fig.height=15, message=F}
nkt_p1 <- plot_UMAP(seur_thym$nkt, col_vector=cols_thym_nkt)
nkt_p2 <- plot_barplot(seur_thym$nkt)

# get marker genes
markergenes_nkt <- get_markergenes(seur_thym$nkt)
markergenes_nkt_list <- markergenes_nkt %>%
  mutate(cluster=as.character(cluster)) %>%
  arrange(cluster) %>%
  filter(p_val_adj<0.05) %>%
  ungroup() %>%
  group_by(cluster) %>%
  top_n(-5, p_val_adj) %>%
  top_n(5, avg_log2FC) %>%
  ungroup() %>%
  pull(gene) %>% unique()

nkt_p3 <- plot_DotPlot(seurobj = seur_thym$nkt, features=markergenes_nkt_list, scaling=T)

# nkt_p1 + nkt_p2 + nkt_p3 + plot_layout(widths=c(1,1,1.5))
nkt_p1 / nkt_p2 / nkt_p3 + plot_layout(heights=c(1,1,2))
# ggsave("~/Projects/phd/data/figures/chapter_02/figs_unfinished/section2/appendix1_markergenes/ch2_suppfigure_nkt_vertical.pdf", width=6, height=13)
```


## MAIT
```{r mait, fig.width=6, fig.height=15, message=F}
mait_p1 <- plot_UMAP(seur_thym$mait, col_vector=cols_thym_mait)
mait_p2 <- plot_barplot(seur_thym$mait)

# get marker genes
markergenes_mait <- get_markergenes(seur_thym$mait)
markergenes_mait_list <- markergenes_mait %>%
  mutate(cluster=as.character(cluster)) %>%
  arrange(cluster) %>%
  filter(p_val_adj<0.05) %>%
  ungroup() %>%
  group_by(cluster) %>%
  top_n(-5, p_val_adj) %>%
  top_n(5, avg_log2FC) %>%
  ungroup() %>%
  pull(gene) %>% unique()

mait_p3 <- plot_DotPlot(seurobj = seur_thym$mait, features=markergenes_mait_list, scaling=T)

# mait_p1 + mait_p2 + mait_p3 + plot_layout(widths=c(1,1,1.5))
mait_p1 / mait_p2 / mait_p3 + plot_layout(heights=c(1,1,2))
# ggsave("~/Projects/phd/data/figures/chapter_02/figs_unfinished/section2/appendix1_markergenes/ch2_suppfigure_mait_vertical.pdf", width=6, height=13)
```


## $\gamma\delta$T
```{r gdt, fig.width=10, fig.height=6, message=F}
gdt_p1 <- plot_UMAP(seur_thym$gdt, col_vector=cols_thym_gdt)
gdt_p2 <- plot_barplot(seur_thym$gdt)

# get marker genes
markergenes_gdt <- get_markergenes(seur_thym$gdt)
markergenes_gdt_list <- markergenes_gdt %>%
  mutate(cluster=as.character(cluster)) %>%
  arrange(cluster) %>%
  filter(p_val_adj<0.05) %>%
  ungroup() %>%
  group_by(cluster) %>%
  top_n(-5, p_val_adj) %>%
  top_n(5, avg_log2FC) %>%
  ungroup() %>%
  pull(gene) %>% unique()

gdt_p3 <- plot_DotPlot(seurobj = seur_thym$gdt, features=markergenes_gdt_list, scaling=T)

# gdt_p1 + gdt_p2 + gdt_p3 + plot_layout(widths=c(1,1,1.5))
(((gdt_p1 / plot_spacer() / gdt_p2) + plot_layout(heights=c(1,0.4,1))) | gdt_p3) + plot_layout(widths=c(1,1.2))
# ggsave("~/Projects/phd/data/figures/chapter_02/figs_unfinished/section2/appendix1_markergenes/ch2_suppfigure_gdt_vertical.pdf", width=10, height=8)
```




# DATA FOR SPATIAL TRANSCRIPTOMICS

## Marker genes
```{r}
# Get marker genes
list_marker_genes <- list(
  "cd4"=markergenes_cd4,
  "cd8"=markergenes_cd8,
  "nkt"=markergenes_nkt,
  "mait"=markergenes_mait,
  "gdt"=markergenes_gdt
)

list_marker_genes <- lapply(list_marker_genes, function(x){
  x %>%
    mutate(clusters_per_lineage=as.character(cluster)) %>%
    arrange(cluster) %>%
    select(gene, clusters_per_lineage, avg_log2FC, p_val_adj) %>%
    filter(p_val_adj<0.05) %>%
    group_by(clusters_per_lineage) %>%
    top_n(-20, p_val_adj) %>%
    top_n(20, avg_log2FC) %>%
    ungroup()
})

final_marker_genes_df <- bind_rows(list_marker_genes)

# sanity checks
# table(final_marker_genes_df$clusters_per_lineage, useNA="ifany")
# max(final_marker_genes_df$p_val_adj)
# max(final_marker_genes_df$avg_log2FC)
# min(final_marker_genes_df$avg_log2FC)

write.csv(final_marker_genes_df, "./data/spatial_transcriptomics/top20_marker_genes_per_thymocyte_lineage.csv")
```


## HVGs
```{r}
final_hvg_df <- data.frame(
  "CD4"=VariableFeatures(seur_thym$cd4),
  "CD8"=VariableFeatures(seur_thym$cd8),
  "iNKT"=VariableFeatures(seur_thym$nkt),
  "MAIT"=VariableFeatures(seur_thym$mait),
  "GD"=VariableFeatures(seur_thym$gdt)
) %>%
  pivot_longer(cols=everything(), values_to = "gene", names_to = "tcell_lineage")

table(final_hvg_df$tcell_lineage)
length(unique(final_hvg_df$gene))
# write.csv(final_hvg_df, "./data/spatial_transcriptomics/list_hvg_per_thymocyte_lineage.csv")
```


# Seurat object with only thymus
```{r}
seur_thymus <- subset(seur_integrated, subset=tissue=="Thymus")
seur_thymus

# saveRDS(seur_thymus, "./data/spatial_transcriptomics/seurat_human_thymus_24_04_04.rds")

table(unique(seur_thymus$clusters_per_lineage) %in% unique(final_marker_genes_df$clusters_per_lineage))
table(unique(seur_thymus$tcell_lineage) %in% unique(final_hvg_df$tcell_lineage))
```





# SESSION INFO
```{r}
sessionInfo()
```


