---
title: "Chapter X - R Notebook"
author: "Salomé Carcy"
date: "`r format(Sys.Date(), '%d %B %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true

---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(fig.width = 5, fig.height = 5,
                      warning=FALSE, message=FALSE,
                      root.dir = "~/Projects/phd/")
```


# IMPORT

## Import librairies
```{r import-librairies}
library(ggplot2)
library(ggrepel)
library(RColorBrewer)
library(cowplot)
library(tidyverse)
library(dplyr)
library(Seurat)
library(SCpubr)
library(patchwork)

source("~/Projects/phd/scripts/colors_universal.R")
```

## Import data
```{r import-data}
# seurat object
seur_integrated <- readRDS("./data/seurat_objects/seurat_human_integrated_object_23_12_01.rds")
DimPlot(seur_integrated, reduction="umap_integrated", cols = cols_integrated)

# gene scores from cNMF
# cnmf_spectra <- read.csv("./data/cnmf/non_imputed_cNMF_allcells.spectra.k_12.dt_0_02.consensus.txt", sep="\t", row.names=1)
cnmf_spectra <- read.csv("./data/cnmf/non_imputed_cNMF_allcells.gene_spectra_score.k_12.dt_0_02.txt", sep="\t", row.names=1)
# table(colnames(cnmf_spectra) %in% VariableFeatures(seur_integrated))
dim(cnmf_spectra)
rownames(cnmf_spectra) <- paste0("GEP", c(2,5,3,1,4,12,6,7,8,10,9,11))
head(cnmf_spectra)
# table(colnames(cnmf_spectra)%in%rownames(seur_integrated))
rowSums(cnmf_spectra)
```




# FUNCTIONS
```{r define-functions}
plot_gep_rank <- function(cnmf_df=cnmf_spectra, genes_to_highlight){
  plist <- list()
  for(gp in paste0("GEP", 3:6)){
    # print(gp)
    df <- NULL
    df <- cnmf_df %>%
      t() %>%
      as.data.frame() %>%
      rownames_to_column("gene") %>%
      pivot_longer(cols = !gene,
                   names_to = "gep",
                   values_to = "value") %>%
      filter(gep == gp) %>%
      mutate(rank = dense_rank(-value))
    
    p <- ggplot(df, aes(x = rank, y = value)) +
      geom_hline(yintercept = 0, linetype = "dashed", color="grey") +
      geom_point(size = 0.5) +
      geom_label_repel(
        data = df %>% filter(gene %in% genes_to_highlight),
        aes(label = gene),
        # nudge_y = 0.001,
        nudge_x = -1000,
        min.segment.length = 0,
        force = 10,
        force_pull = 0.01,
        max.time=2,
        max.overlaps = Inf
      ) +
      labs(x = "rank", y = "regression coefficient", title = gp) +
      ylim(c(-0.002, 0.0027)) +
      scale_x_continuous(expand=expansion(mult=0.2))+
      theme_classic() +
      theme(panel.border = element_rect(fill = NA),
            axis.line = element_blank())
    p <- ggrastr::rasterise(p, layers="Point", dpi=300)
    plist[[gp]] <- p
  }
  
  pcombined <- plot_grid(plotlist = plist, nrow=1)
  
  return(pcombined)
}
```



# RANK GENES FOR EACH GEP

## GEP3
```{r contribution-gep3-genes, fig.width=15, fig.height=5}
plot_gep_rank(
  genes_to_highlight =c(
    "SELL",
    "CCR7",
    "TCF7",
    "LEF1",
    "IL7R",
    "FOXP1",
    # "SATB1",
    "CCR7",
    "KLF2",
    "IL6R",
    "IL4R",
    "CD27"
    # "SOX4",
    # "ID3"
  )
)
# ggsave("./data/figures/chapter_03/figs_unfinished/section2/ch3_fig15_contribution_genes_gep3.pdf", width=15, height = 4)
```

## GEP4
```{r contribution-gep4-genes, fig.width=15, fig.height=5}
# cnmf_spectra %>%
#     t() %>%
#     as.data.frame() %>%
#     rownames_to_column("gene") %>%
#     pivot_longer(cols = !gene,
#                  names_to = "gep",
#                  values_to = "value") %>%
#     filter(gep == "GEP4") %>%
#     mutate(rank = dense_rank(-value)) %>%
#   arrange(-value)

plot_gep_rank(
  genes_to_highlight =c(
    # "IL7R",
    # "CXCR3",
    "CCR4",
    "IL6R",
    "GPR183",
    "FOS",
    "JUN",
    "JUNB",
    "CD69",
    "AHR"
    # "GATA3"
  )
)
# ggsave("./data/figures/chapter_03/figs_unfinished/section2/ch3_fig15_contribution_genes_gep4.pdf", width=15, height = 4)
```


## GEP5
```{r contribution-gep5-genes, fig.width=15, fig.height=5}
plot_gep_rank(
  genes_to_highlight =c(
    # "IL7R",
    # "CXCR3",
    # "CCR5",
    "CCR6",
    "GZMK",
    # "GZMA",
    "PRF1",
    "KLRB1",
    "EOMES",
    "RORC",
    "RORA",
    "IL23R",
    "ZBTB16",
    "CEBPD",
    "IL12RB2",
    "IL18R1"
    # "CCL5"
  )
)
# ggsave("./data/figures/chapter_03/figs_unfinished/section2/ch3_fig15_contribution_genes_gep5.pdf", width=15, height = 4)
```


## GEP6
```{r contribution-gep6-genes, fig.width=15, fig.height=5}
plot_gep_rank(
  genes_to_highlight =c(
    # "IL7R",
    # "CXCR3",
    # "CCR5",
    "CX3CR1",
    "GZMB",
    "GZMH",
    "PRF1",
    "GNLY",
    "TBX21",
    "IFNG",
    # "NCAM1",
    "TYROBP",
    "KLRD1"
  )
)
# ggsave("./data/figures/chapter_03/figs_unfinished/section2/ch3_fig15_contribution_genes_gep6.pdf", width=15, height = 4)
```






# SESSION INFO
```{r}
sessionInfo()
```


