---
title: "Chapter X - R Notebook"
author: "Salomé Carcy"
date: "`r format(Sys.Date(), '%d %B %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true

---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(fig.width = 5, fig.height = 5,
                      warning=FALSE, message=FALSE,
                      root.dir = "~/Projects/phd/")
```


# IMPORT

## Import librairies
```{r import-librairies}
library(ggplot2)
library(RColorBrewer)
library(cowplot)
library(tidyverse)
library(dplyr)
library(Seurat)
library(SCpubr)
library(patchwork)
library(pheatmap)
library(ComplexHeatmap)

source("~/Projects/phd/scripts/colors_universal.R")
```

## Import data
```{r import-data}
seur_integrated <- readRDS("./data/seurat_objects/seurat_human_integrated_object_23_12_01.rds")
DimPlot(seur_integrated, reduction="umap_integrated", cols = cols_integrated)
```

SCENIC output:
```{r}
regulons  <-  read.csv(
  "./data/scenic/nes2_maskdropouts_full_obj_seurat_filtered_harmony_08_28_23_raw_counts_100_multirun_reg100-target95_regulons_pruned_final_GEP_INTERSECTION_TARGET_PRUNED_auc_mtx.csv",
  row.names  =  1
  )
regulons$cell_id  <-  rownames(regulons)
head(regulons, 5)

regulons_to_keep <- read_table("./data/scenic/regulons_to_keep_min5_target.txt", col_names = FALSE)$X1
```




# FUNCTIONS
```{r define-functions}
make_bold_names <- function(mat, rc_fun, rc_names) {
  bold_names <- rc_fun(mat)
  ids <- rc_names %>% match(rc_fun(mat))
  ids %>%
    walk(
      function(i)
        bold_names[i] <<-
        bquote(bold(.(rc_fun(mat)[i]))) %>%
        as.expression()
    )
  bold_names
}
```




# ANALYSIS

## Laurent pheatmap
```{r pheatmap-laurent, fig.width=20, fig.height=20}
# Downsample Seurat object to 10,000 cells
downsampled_seurat <- subset(seur_integrated, cells = sample(Cells(seur_integrated), 10000))

# Extract metadata and join with regulons data
metadata <- downsampled_seurat@meta.data %>% 
  rownames_to_column("cell_id") %>%
  dplyr::select(cell_id, donor_sex, donor_id, batch_id, tissue, clusters_integrated_data, GEP_with_max_usage)
metadata_regulons <- left_join(metadata, regulons, by = "cell_id")


# Order and factorize data
# metadata_regulons$new_clusters <- factor(metadata_regulons$new_clusters, levels = seq(0,17, 1))
# metadata_regulons <- metadata_regulons[order(metadata_regulons$new_clusters, decreasing = FALSE),]
# head(metadata_regulons, 3)

# Prepare data for analysis
data <- metadata_regulons[,c(1,8:348)]
rownames(data) <- data$cell_id
data$cell_id <- NULL
data <- t(data) # Transpose data
data[1:5, 1:5]


# Filter data based on regulons to keep
select_data <- data[regulons_to_keep,]
dim(select_data)
select_data[1:5, 1:5]

# metadata_df  <-  downsampled_seurat@meta.data
# metadata_df  <-  metadata_df  %>%  dplyr::select(cell_id,  Sex,  Donor,  Batch,  Tissue,  new_clusters,  new_clusters_id, gep_assign)
# metadata_df_regulons  <-  left_join(metadata_df,  regulons  ,  by  =  "cell_id")
# metadata_df_regulons$new_clusters  <-  factor(metadata_df_regulons$new_clusters,  levels  =  seq(0,17,  1))
# metadata_df_regulons  <-  metadata_df_regulons[order(metadata_df_regulons$new_clusters,  decreasing  =  F),]
# dim(metadata_df_regulons)
# metadata_df_regulons[1:3,  1:10]

# data_2  <-  metadata_df_regulons  %>%  select(-Sex,  -Donor,  -Batch,  -Tissue, -new_clusters_id, -new_clusters, -gep_assign)
# data_2[1:3,  1:7]
# rownames(data_2) <- data_2$cell_id
# data_2$cell_id <- NULL
# data_2[1:3,  1:7]
# data_2 <- t(data_2)
# data_2[1:3,  1:7]
# 
# select_data_2  <-  as.data.frame(data_2)  %>%  filter(row.names(data_2)  %in%  regulons_to_keep)
# select_data_2[1:5,  1:5]
# dim(select_data_2)
# select_data_2 <- t(select_data_2)
# select_data_2 <- as.data.frame(select_data_2)
# select_data_2$new_clusters_id <- metadata_df_regulons$new_clusters_id

select_data_2 <- as.data.frame(t(select_data))
table(rownames(select_data_2)==metadata_regulons$cell_id, useNA="ifany")
select_data_2$clusters_integrated_data <- metadata_regulons$clusters_integrated_data

# Calculate the 90th percentile for each column by group
percentiles_90 <- select_data_2 %>%
  select_if(is.numeric) %>%
  summarise(across(everything(), ~ quantile(., 0.90, na.rm = TRUE)))

result <- select_data_2 %>%
  group_by(clusters_integrated_data) %>%
  summarise(across(where(is.numeric), 
                   ~ mean(. > percentiles_90[[cur_column()]], na.rm = TRUE), 
                   .names = "prop_above_{.col}"))

# Filter the percentiles dataframe to keep only columns with at least one value > 10%
cols_to_keep <- result %>%
  select(-clusters_integrated_data) %>%
  summarise_all(~any(. > 0.20)) %>%
  as.data.frame() %>%
  names(.)[unlist(.)] %>% colnames() %>% gsub("prop_above_|_p90", "", .)

# data  <-  metadata_df_regulons  %>%  select(-Sex,  -Donor,  -Batch,  -Tissue, -new_clusters_id, -new_clusters, -gep_assign)
# data[1:3,  1:7]
# rownames(data) <- data$cell_id
# data$cell_id <- NULL
# data[1:3,  1:7]
# dim(data)
# data  <-  t(data) 

select_data_to_plot  <-  as.data.frame(data)  %>%  filter(row.names(data)  %in%  cols_to_keep)
dim(select_data_to_plot)
#check  the  number  of  columns  with  regulons
select_data_to_plot[1:5,  1:5]


# Set up colors and other aesthetics for heatmap
# heat_colors <- scico(100, palette = "vik")
# colors_clusters <- c("0"  =  "#f4c40f",  "1"  =  "#b75347",  "2"  =  "#d8443c",  "3"  =  "#e09351",  "4"  =  "#2b9b81",  
#                      "5"  =  "#421401",  "6"  =  "#92c051",  "7"  =  "#9f5691",  "8"  =  "#17154f",  "9"  =  "#74c8c3",  
#                      "10"  =  "#5a97c1",  "11"  =  "gold",  "12"  =  "#a40000",  "13"  =  "#72bcd5",  "14"  =  "grey50",
#                      "15"  =  "orange",  "16"  =  "blueviolet",  "17"  =  "#0a2e57") 
# names(colors_clusters) <- seq(0, 17)

# Prepare metadata for annotation
# meta <- metadata_df_regulons[,1:8]
# meta <- meta %>% filter(!new_clusters == 18)
# meta$new_clusters <- factor(meta$new_clusters, seq(0, 17, 1))
# rownames(meta) <- meta$cell_id
dim(metadata)
meta <- metadata
rownames(meta) <- meta$cell_id

# Prepare GEP assign and tissue colors
heat_colors  <-  scico(100,  alpha  =  NULL,  begin  =  0,  end  =  1,  direction  =  1,  palette  =  "vik",  categorical  =  FALSE)

# colors_clusters  <-  c("0"  =  "#f4c40f",  "1"  =  "#b75347",  "2"  =  "#d8443c",  "3"  =  "#e09351",  "4"  =  "#2b9b81",  
#                        "5"  =  "#421401",  "6"  =  "#92c051",  "7"  =  "#9f5691",  "8"  =  "#17154f",  "9"  =  "#74c8c3",  
#                        "10"  =  "#5a97c1",  "11"  =  "gold",  "12"  =  "#a40000",  "13"  =  "#72bcd5",  "14"  =  "grey50",
#                        "15"  =  "orange",  "16"  =  "blueviolet",  "17"  =  "#0a2e57")

# colors_tissues <- c("#72bcd5", "#a40000")
# names(colors_tissues) <- unique(meta$Tissue)

# colors_GEPs <-  c("gep1"  =  "#f5bb50",  "gep2"  =  "#ada43b",  "gep3"  =  "#b0799a",  "gep4"  =  "#f6b3b0",  "gep5"  =  "#bf3729",  
#                   "gep6"  =  "#17154f",  "gep7"  =  "#355828",  "gep8"  =  "#e48171",  "gep9"  =  "#2f357c",  "gep10"  =  "#6c5d9e",  
#                   "gep11"  =  "#e69b00")


# Reorder rows in the data based on specific order
the_order <- c("PBX1", "ETV6", "HOXA10", "MTF2", "ZNF711", "ETS2", "HES1", "FOXO6", "HOXA3",
               "SOX4", "ILF2", "TFDP2", "YBX1", "NFYB", "MYB", "NONO", "SFPQ", "CHD1", "NR3C1", "HDAC2",
               "HMGA1", "FOXM1", "TFDP1", "E2F1", "MYBL2", "E2F8", "E2F2", "E2F7", "ZNF69",
               "BCL11A", "STAT5A", "KLF5" , "VDR", "IRF8",
               "BACH2", "IRF4", "NFKB1", "REL", "ZFX", "ZNF333", "RFX3", "VEZF1", "EGR2", "EGR3", "EGR1","SMAD3", "STAT6",
               "TCF3", "ETV5", "GATA3", "RAD21", "ELF1", "IKZF2", "BCL11B", "BCL6", "LEF1", "NFATC1", "SREBF2", "HOXB2", "PPARG", 
               "NR2C2", "HMGXB4", "ELK1", "RFX5", 
               "RXRA", "IKZF1", "YY1", "BPTF", "REST", "EP300", "MAX", "FOSL1", "GTF2I",
               "CEBPA", "FOXP3", "NR2F1", "ZNF610", "IRF6", 
               "IRF2" , "ELK4", "IRF7", "STAT2", 
               "FOXO1", "FOXP1", "STAT1", "KLF4",
               "BCLAF1", "KLF9", "ETS1", "FOS",  "JUNB", "JUN", "FOSB",  "JUND", 
               "ELK3", "MBD2", "CREM", "NFE2L2", "NR1D2", "XBP1", "MYBL1", "RORA", "MAF", "CEBPD", "FOSL2", "EOMES",
               "IRF1" , "KLF2",  "KLF6", "RUNX3", "PRDM1", "FLI1", "KLF12", "IKZF3", "ZBTB20", 
               "ELF4", "ZBTB7A", "NFATC2", "TBX21",  "NFATC3", "ZBTB44", "KLF3", 
               "ATF4", "E2F3", "KLF13", "ETV7", "HCLS1", "HES7", "HNF1B", "PURA", "SIN3A",
               "GATA6", "MTF1",
               "IRF5", 
               "VPS72" , "ZBTB25",
               "CLOCK", "ELF2", "GATAD1", "KLF8", "MYC", "NFIC", "SP1", "SP2", "SP3", "TAF6", "ZBTB11", "ZFY", "ZNF460")
length(the_order)
dim(select_data_to_plot)
table(the_order %in% rownames(select_data_to_plot))

# order rows and columns
cells_order <- rownames(meta %>% arrange(clusters_integrated_data))
select_data_to_plot <- select_data_to_plot[the_order,cells_order] 

# column_cuts <- which(duplicated(metadata_df_regulons$new_clusters) == FALSE)
# column_cuts <- column_cuts[2:length(column_cuts)] - 1
# # Values to be removed
# values_to_remove <- c(9542, 9361, 7267)
# 
# # Remove the specified values
# column_cuts <- column_cuts[!column_cuts %in% values_to_remove]

# pdf("./data/figures/chapter_03/figs_unfinished/section3/ch3_fig20_pheatmap_laurent.pdf", width=15, height=15)
# pheatmap::pheatmap(
#   select_data_to_plot,
#   color = heat_colors,  
#   breaks = seq(-5, 5, by = 0.1),
#   scale = "row",
#   cellheight = 6,
#   cluster_rows = FALSE,
#   cluster_cols = FALSE,
#   show_colnames = FALSE,
#   labels_row=make_bold_names(matrix_auc_test, rownames, c("ELK3", "MBD2", "CREM", "NFE2L2", "NR1D2", "XBP1", "MYBL1", "RORA", "MAF", "CEBPD", "FOSL2")),
#   # gaps_row = c(9, 14, 19, 28, 38, 41, 46, 60, 64, 73, 77, 82, 88, 94, 105, 122),# Specify gaps in rows
#   # gaps_col = column_cuts, 
#   annotation_col = meta %>% dplyr::select(c(tissue, clusters_integrated_data, GEP_with_max_usage)),
#   annotation_colors = list(
#     clusters_integrated_data = cols_integrated,
#     GEP_with_max_usage = cols_GEPs,
#     tissue = cols_tissue
#   ),
#   fontsize_row = 6, width = 10, height = 10,
#   main = "Scenic Run with Full Data \n ± 10Kb \n with AUC scores row scaled"
# )
# dev.off()
```

Laurent's figure in complex heatmap to rasterize
```{r, fig.width=20, fig.height=20}
meta <- meta[cells_order,]

# pdf("./data/figures/chapter_03/figs_unfinished/section3/ch3_fig20_pheatmap_laurent2.pdf", width=15, height=15)
Heatmap(
  t(scale(t(select_data_to_plot))),
  cluster_rows=F,
  cluster_columns = F,
  # col = c("#001260", "#EAE5E3", "#590007"),
  # col=circlize::colorRamp2(seq(min(t(scale(t(select_data_to_plot)))), max(t(scale(t(select_data_to_plot)))), length = 3), c("#001260", "#EEEEEE", "#590007"), space = "RGB"),
  # cellheight = 6,
  show_column_names = FALSE,
  row_labels=make_bold_names(select_data_to_plot, rownames, c("ELK3", "MBD2", "CREM", "NFE2L2", "NR1D2", "XBP1", "MYBL1", "RORA", "MAF", "CEBPD", "FOSL2")),
  top_annotation = HeatmapAnnotation(
    gep_with_max_usage=meta %>% pull(GEP_with_max_usage),
    clusters_integrated_data=meta %>% pull(clusters_integrated_data),
    tissue=meta %>% pull(tissue),
    col=list(
      clusters_integrated_data = cols_integrated,
      gep_with_max_usage = cols_GEPs,
      tissue = cols_tissue
    )
  )
)
# dev.off()
```



## Heatmap with median regulon
```{r heatmap-median-regulon, fig.height=20, fig.width=20}
regulons_of_interest <- regulons[, the_order]
dim(regulons_of_interest)
regulons_of_interest[1:5,1:5]

# add metadata
table(rownames(regulons_of_interest)==rownames(seur_integrated@meta.data), useNA="ifany")
df_auc <- regulons_of_interest %>%
  rownames_to_column("cellid") %>%
  left_join(
    seur_integrated@meta.data %>%
      as.data.frame() %>%
      rownames_to_column("cellid") %>%
      select(cellid, clusters_integrated_data, tissue, tcell_lineage, GEP_with_max_usage),
    by="cellid"
  ) %>%
  relocate(clusters_integrated_data, tissue, tcell_lineage, GEP_with_max_usage, .after=cellid) %>%
  pivot_longer(cols=!c(cellid, clusters_integrated_data, tissue, tcell_lineage, GEP_with_max_usage), names_to="regulon", values_to="auc") %>%
  # choose how I wanna group cells
  # mutate(columns=paste(clusters_integrated_data, tissue, tcell_lineage, sep="_")) %>%
  mutate(columns=GEP_with_max_usage) %>%
  # get median regulon auc per cluster and tissue and lineage
  # group_by(clusters_integrated_data, tissue, tcell_lineage, regulon) %>%
  group_by(columns, regulon) %>%
  summarise(
    auc_mean=mean(auc),
    auc_sd=sd(auc),
    auc_median=median(auc)
    ) %>%
  ungroup()
# length(unique(df_auc$regulon))==length(the_order)

matrix_auc <- df_auc %>%
  select(columns, regulon, auc_median) %>%
  pivot_wider(names_from=columns, values_from=auc_median)
  # select(columns, regulon, auc_mean) %>%
  # pivot_wider(names_from=columns, values_from=auc_mean)
matrix_auc <- as.data.frame(matrix_auc)
rownames(matrix_auc) <- matrix_auc$regulon
matrix_auc$regulon <- NULL


# metadata for pheatmap
df_metadata <- df_auc %>%
  # select(columns, clusters_integrated_data, tissue, tcell_lineage) %>%
  select(columns) %>%
  distinct() %>%
  arrange(columns)
df_metadata <- as.data.frame(df_metadata)
rownames(df_metadata) <- df_metadata$columns

# reorder columns matrix
table(colnames(matrix_auc) %in% rownames(df_metadata), useNA="ifany")
matrix_auc <- matrix_auc[the_order,paste0("GEP", 1:11)]

# remove rows that would have NAs?
# matrix_auc_test <- t(apply(matrix_auc, 1, function(x) scale(x)))
# colnames(matrix_auc_test) <- colnames(matrix_auc)
# giveNAs = which(is.na(as.matrix(dist(matrix_auc_test))),arr.ind=TRUE)
# head(giveNAs)
matrix_auc <- matrix_auc[rownames(matrix_auc)!="IRF5",]

# pheatmap
# pdf("./data/figures/chapter_03/figs_unfinished/section3/ch3_fig20_pheatmap_median_auc_per_gep_assign.pdf", width=10, height=15)
pheatmap::pheatmap(
  matrix_auc,
  color = heat_colors,  
  # breaks = seq(-5, 5, by = 0.1),
  scale = "row",
  # cluster_rows = F,
  cluster_cols = F,
  # gaps_row = c(9, 14, 19, 28, 38, 41, 46, 60, 64, 73, 77, 82, 88, 94, 105, 122),
  labels_row=make_bold_names(matrix_auc_test, rownames, c("ELK3", "MBD2", "CREM", "NFE2L2", "NR1D2", "XBP1", "MYBL1", "RORA", "MAF", "CEBPD", "FOSL2")),
  annotation_col = df_metadata,
  annotation_colors = list(
    clusters_integrated_data = cols_integrated,
    columns = cols_GEPs,
    tcell_lineage=cols_lineages,
    tissue = cols_tissue
  )
)
# dev.off()
```



## Scatterplot GEP5 usage and GEP5 regulons AUC
```{r correlation-gep5-usage-regulons-AUC, fig.height=10, fig.width=10}
regulons_of_interest %>%
  select(ELK3, MBD2, CREM, NFE2L2, NR1D2, XBP1, MYBL1, RORA, MAF, CEBPD, FOSL2, FOXP1, KLF4, KLF9) %>%
  rownames_to_column("cellid") %>%
  left_join(
    seur_integrated@meta.data %>%
      as.data.frame() %>%
      rownames_to_column("cellid") %>%
      select(cellid, clusters_integrated_data, tissue, tcell_lineage, GEP_with_max_usage, GEP5_usage),
    by="cellid"
  ) %>%
  relocate(clusters_integrated_data, tissue, tcell_lineage, GEP_with_max_usage, GEP5_usage, .after=cellid) %>%
  filter(tissue=="PBMC") %>%
  pivot_longer(cols=!c(cellid, clusters_integrated_data, tissue, tcell_lineage, GEP_with_max_usage, GEP5_usage), names_to="regulon", values_to="auc") %>%
  # PLOT
  ggplot(aes(x=GEP5_usage, y=auc))+
  facet_wrap(~regulon)+
  geom_point(size=0.1)
```





# SESSION INFO
```{r}
sessionInfo()
```


