name: environment_phd
channels:
  - anaconda
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - numpy
  - pandas
  - r-base=4.3.1
  - r-markdown=2.25
  - r-seurat=4.4.0
  - r-ggplot2=3.4.4
  - r-cowplot=1.1.2
  - bioconductor-deseq2=1.42.0
  - r-tidyverse=2.0.0